require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'Cropfit' do
  config = use_native_modules!

  # Flags change depending on the env values.
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
    :fabric_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  permissions_path = '../node_modules/react-native-permissions/ios'
  
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pod 'react-native-encrypted-storage', :path => '../node_modules/react-native-encrypted-storage'

  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNShare', :path => '../node_modules/react-native-share'


 
 pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  target 'CropfitTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
