


export const colors = {
    background_color: '#fafafa',
    white_color: '#ffffff',
    black_color: '#000000',
    landing_background: '#016130',
    landing_border: '#01a552',
    text_Color: '#333333',
    subText_Color: '#666666',
    search_placeholder: '#8B8E8E',
    line_background: 'rgba(112, 112, 112, 0.2)',
    lite_black: 'rgba(0,0,0,0.3)',
    lite_naviBlue: '#b1d2f2'

};

export const fonts = {
    MONTSERRAT_BOLD: 'Montserrat-Bold',
    MONTSERRAT_Light: 'Montserrat-Light',
    MONTSERRAT_MEDIUM: 'Montserrat-Medium',
    MONTSERRAT_REGULAR: 'Montserrat-Regular',
    MONTSERRAT_SIMEBOLD: 'Montserrat-SemiBold',
};

export const images = {
    CROPFITWHITELOGO: require('../assets/images/farmfit_logo_white.png'),
    CROPFITBLACKLOGO: require('../assets/images/farmfit_logo_black.png'),
    GETSTARTARROW: require('../assets/images/get_started_arrow.png'),
    HEADINGBACKGROUNDIMAGE: require('../assets/images/heading_background_image.png'),
    LANGUAGEICON: require('../assets/images/language_icon.png'),
    LANGUAGEBLACKICON: require('../assets/images/language_icon_black.png'),
    NOTIFICATIONICON: require('../assets/images/notification_icon.png'),
    OTPICON: require('../assets/images/otp_icon.png'),
    SEARCHICON: require('../assets/images/Search_Icon.png'),
    BACKICON: require('../assets/images/back_icon.png'),
    HOMEICON: require('../assets/images/home_icon.png'),
    HOMEACTIVEICON: require('../assets/images/home_icon_active.png'),
    BUYICON: require('../assets/images/buy.png'),
    BUYACTIVEICON: require('../assets/images/buy_active.png'),
    SELLCON: require('../assets/images/sell.png'),
    SELLACTIVEICON: require('../assets/images/sell_active.png'),
    BIDESICON: require('../assets/images/bids.png'),
    BIDSACTIVEICON: require('../assets/images/bids_active.png'),
    BACKICON: require('../assets/images/back.png'),
    LOCATIONICON: require('../assets/images/location_home.png'),
    DROPDOWNARROWICON: require('../assets/images/dropdown_arrow.png'),
    LANGUAGECLOSEICON: require('../assets/images/language_closeIcon.png'),
    PHONEICON: require('../assets/images/phone_icon.png'),
    EMPTYPROFILEICON: require('../assets/images/empty_profile.png'),
    TICKICON: require('../assets/images/tick_icon.png'),
    STARICON: require('../assets/images/star_icon.png'),
    RIGHTARROWICON: require('../assets/images/right_arrow.png'),
    DOBICON: require('../assets/images/dob_icon.png'),
    EDITPROFILEICON: require('../assets/images/edit_profile_icon.png'),
    EDITICON: require('../assets/images/edit_icon.png'),
    FARMICON: require('../assets/images/farm_icon.png'),
    LOCATIONPROFILEICON: require('../assets/images/location_icon.png'),
    LOGOUTICON: require('../assets/images/Logout_icon.png'),
    PERSONALICON: require('../assets/images/personal_icon.png'),
    TICKWHITEICON: require('../assets/images/white_tick_icon.png'),
    LOTSICON: require('../assets/images/lot_icon.png'),
    BIDSICON: require('../assets/images/bids_icon.png'),
    PLAYICON: require('../assets/images/play_icon.png'),
    VIDEOSICON: require('../assets/images/video_icon.png'),
    BANNERREFERFRIEND: require('../assets/images/banner_refer_friend.png'),
    ORGANICLOGO: require('../assets/images/organic_logo.png'),
    BROWSEFILE: require('../assets/images/browse_file_icon.png'),
    TAKEPHOTO: require('../assets/images/take_photo_icon.png'),
    REMOVEICON: require('../assets/images/remove_icon.png'),
    RUPEESICON: require('../assets/images/Check_Rates_Icon.png'),
    DOCUMENTICON: require('../assets/images/document_icon.png'),
    UPLOADMANDIICON: require('../assets/images/upload_mandi_icon.png'),
    VIEWENQUIRIESICON: require('../assets/images/View_Enquires_icon.png'),
    SELECTEDBOX: require('../assets/images/selected_category.png'),
    UNSELECTEDBOX: require('../assets/images/checkBox.png'),
    HELPLINE: require('../assets/images/helpLine_icon.png'),
    CROPCLINIC: require('../assets/images/crop_clinic_img.png'),
    DELETEACCOUNT: require('../assets/images/acc_delete.png'),
    WARNINGDELETE: require('../assets/images/warning_delete.png'),
    SHAREIMAGE: require('../assets/images/share.png'),
    NOTIFICATION: require('../assets/images/notification.png'),
    EMPTYNOTIFICATION: require('../assets/images/empty_notification.png'),
    NOTIFICATIONLOGO: require('../assets/images/notification-logo.png'),
    BIDIMAGE: require('../assets/images/bidImage.png'),
    BOOKMARKICON: require('../assets/images/bookmark.png'),
    EMPTYBOOKMARKICON: require('../assets/images/empty-bookmark.png'),
    ACTIVITYWHITE: require('../assets/images/activity_white.png'),
    ACTIVITYBID: require('../assets/images/viewbids.png'),
    ACTIVITYSELL: require('../assets/images/viewbuy.png'),
    ACTIVITYENQUIRY: require('../assets/images/enquiry.png'),
    ACTIVITYLOTICON: require('../assets/images/myactivity-loticon.png'),
    MYACTIVITYLOTIMAGE: require('../assets/images/loticon.png'),
    PRIVACY_POLICY: require('../assets/images/privacy_policy.png'),
TERMSANDCONDITION: require('../assets/images/term_and_condition.png'),

};
